import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { getModelToken } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { AppModule } from '../app.module';
import { Product, ProductDocument } from './schemas/product.schema';
import { User, UserDocument } from './schemas/user.schema';
import * as bcrypt from 'bcrypt';
async function seed() { const app = await NestFactory.createApplicationContext(AppModule); const products = app.get<Model<ProductDocument>>(getModelToken(Product.name)); await products.bulkWrite([{ updateOne: { filter: { slug: 'sassy-hi' }, update: { $set: { slug: 'sassy-hi', name: 'Sassy Hi', profile: 'strawberry', description: 'A bright strawberry profile.', price: 499, compareAt: 599, packs: [{ quantity: 5, price: 199, label: 'Curious · 5 gummies' }, { quantity: 10, price: 349, label: 'Daily · 10 gummies' }, { quantity: 20, price: 499, label: 'Ritual · 20 gummies' }], ingredients: ['Vijaya leaf extract', 'Pectin', 'Natural strawberry flavour', 'Cane sugar'], notes: ['Strawberry', 'Soft', 'Bright'], verificationRequired: true, publishReady: true } }, upsert: true } }, { updateOne: { filter: { slug: 'sassy-attitude' }, update: { $set: { slug: 'sassy-attitude', name: 'Sassy Attitude', profile: 'citrus', description: 'A crisp citrus profile.', price: 499, compareAt: 599, packs: [{ quantity: 5, price: 199, label: 'Curious · 5 gummies' }, { quantity: 10, price: 349, label: 'Daily · 10 gummies' }, { quantity: 20, price: 499, label: 'Ritual · 20 gummies' }], ingredients: ['Vijaya leaf extract', 'Pectin', 'Natural citrus flavour', 'Cane sugar'], notes: ['Orange', 'Crisp', 'Grounded'], verificationRequired: true, publishReady: true } }, upsert: true } }]); const users = app.get<Model<UserDocument>>(getModelToken(User.name)); const adminEmail = process.env.ADMIN_EMAIL?.toLowerCase(); const adminPassword = process.env.ADMIN_PASSWORD; if (adminEmail && adminPassword && adminPassword !== 'replace-before-seeding') { await users.findOneAndUpdate({ email: adminEmail }, { $set: { email: adminEmail, firstName: process.env.ADMIN_FIRST_NAME ?? 'HITUDE Admin', role: process.env.ADMIN_ROLE ?? 'super_admin', emailVerified: true, passwordHash: await bcrypt.hash(adminPassword, 12) } }, { upsert: true, new: true }); console.log(`Admin upserted: ${adminEmail}`); } else { console.warn('Admin not seeded. Set ADMIN_EMAIL and a non-placeholder ADMIN_PASSWORD in .env first.'); } await app.close(); }
seed();
