import { ConflictException, Injectable, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { InjectModel } from '@nestjs/mongoose';
import * as bcrypt from 'bcrypt';
import { Model } from 'mongoose';
import { User, UserDocument } from '../database/schemas/user.schema';
import { RedisService } from '../infrastructure/redis/redis.service';
import { RegisterDto } from './dto/register.dto';
@Injectable()
export class AuthService {
  constructor(@InjectModel(User.name) private readonly users: Model<UserDocument>, private readonly jwt: JwtService, private readonly redis: RedisService) {}
  async register(dto: RegisterDto) { if (!dto.consent) throw new UnauthorizedException('Privacy policy and terms consent is required'); const email = dto.email.toLowerCase(); if (await this.users.exists({ email })) throw new ConflictException('An account with this email already exists'); const passwordHash = await bcrypt.hash(dto.password, 12); const user = await this.users.create({ email, passwordHash, firstName: dto.firstName, marketingConsent: dto.consent }); const verificationToken = this.jwt.sign({ sub: user._id.toString(), purpose: 'email-verification' }, { secret: process.env.JWT_ACCESS_SECRET, expiresIn: '30m' }); await this.redis.set(`email-verification:${user._id}`, verificationToken, 1800); return { user: this.publicUser(user), tokens: this.tokens(user) }; }
  async login(email: string, password: string) { const user = await this.users.findOne({ email: email.toLowerCase() }); if (!user) throw new UnauthorizedException('Email or password is incorrect'); if (user.lockedUntil && user.lockedUntil > new Date()) throw new UnauthorizedException('Account temporarily locked. Try again later.'); const valid = await bcrypt.compare(password, user.passwordHash); if (!valid) { user.failedLoginAttempts += 1; if (user.failedLoginAttempts >= 5) { user.lockedUntil = new Date(Date.now() + 15 * 60 * 1000); user.failedLoginAttempts = 0; } await user.save(); throw new UnauthorizedException('Email or password is incorrect'); } user.failedLoginAttempts = 0; user.lockedUntil = undefined; await user.save(); return { user: this.publicUser(user), tokens: this.tokens(user) }; }
  async refresh(refreshToken?: string) { try { if (!refreshToken) throw new Error('missing token'); const payload = this.jwt.verify<{ sub: string; role: string }>(refreshToken, { secret: process.env.JWT_REFRESH_SECRET }); const user = await this.users.findById(payload.sub); if (!user) throw new Error('missing user'); return this.tokens(user); } catch { throw new UnauthorizedException('Refresh session expired'); } }
  async verifyEmail(token: string) { try { const payload = this.jwt.verify<{ sub: string; purpose: string }>(token, { secret: process.env.JWT_ACCESS_SECRET }); if (payload.purpose !== 'email-verification') throw new Error('invalid purpose'); const stored = await this.redis.get<string>(`email-verification:${payload.sub}`); if (stored && stored !== token) throw new Error('token mismatch'); await this.users.findByIdAndUpdate(payload.sub, { emailVerified: true }); await this.redis.del(`email-verification:${payload.sub}`); return { ok: true }; } catch { throw new UnauthorizedException('Email verification link is invalid or expired'); } }
  private tokens(user: UserDocument) { return { accessToken: this.jwt.sign({ sub: user._id.toString(), role: user.role }, { secret: process.env.JWT_ACCESS_SECRET, expiresIn: '15m' }), refreshToken: this.jwt.sign({ sub: user._id.toString(), role: user.role }, { secret: process.env.JWT_REFRESH_SECRET, expiresIn: '30d' }) }; }
  private publicUser(user: UserDocument) { return { id: user._id.toString(), email: user.email, firstName: user.firstName, role: user.role, emailVerified: user.emailVerified }; }
}
